# Generated by Django 5.1.3 on 2024-11-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_profileembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="character",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
