# Generated by Django 5.1.3 on 2024-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_userprofile_character_userprofile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accepted_hobbies",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rejected_hobbies",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
