# Generated by Django 5.1.3 on 2024-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_userprofile_accepted_hobbies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
