# Generated by Django 5.1.3 on 2024-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobby", "0002_hobbyembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="hobby",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
